In [1]:
from langchain_community.document_loaders import DataFrameLoader
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

import pandas as pd

C:\Users\mahdi\AppData\Local\Temp\ipykernel_45244\3664084969.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import DataFrameLoader

In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
books = pd.read_csv("books_preprocessed.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

Load the descriptions from the dataframe

DONOTINCLUDE deviated from vid here: (can delete tagged_descriptions.txt)

In [4]:
# Load the descriptions directly from your existing DataFrame
loader = DataFrameLoader(books, page_content_column="tagged_description")
documents = loader.load()

documents[0]

Document(metadata={'isbn13': 9780002005883, 'isbn10': '0002005883', 'title': 'Gilead', 'authors': 'Marilynne Robinson', 'categories': 'Fiction', 'thumbnail': 'http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'description': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.', 'published_year': 2004.0, 'average_rating': 3.85, 'num_pages': 247.0, 'ratings_count': 361.0, 'title_and_subtitle': 'Gilead'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [5]:
# Initialize BAAI/bge-large-en-v1.5 locally
embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-large-en-v1.5",
    model_kwargs={"device": "cuda"}, # uses gpu for better processing
    encode_kwargs={"normalize_embeddings": True},
    query_encode_kwargs={
        "prompt": "Represent this sentence for searching relevant passages: ",
        "normalize_embeddings": True,
    }
)

# Build the vector database
db_books = Chroma.from_documents(
    documents,
    embedding=embeddings
)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [6]:
sample_query = "heartwarming book involving dragons and wonder"
docs = db_books.similarity_search(sample_query, k = 10)

# prints just titles from the search results
for i, doc in enumerate(docs, 1):
    print(f"{i}. {doc.metadata.get('title')}")

# prints full details
docs

1. The Dragon's Eye
2. The Search for Power
3. The Dastard
4. Firedrake
5. The Last of the Really Great Whangdoodles
6. The Smoke Thief
7. Spindle's End
8. The Day of the Tempest
9. Wolfskin
10. Rose Daughter

[Document(id='d647074d-a468-4a1f-affd-254893a98092', metadata={'isbn13': 9780763628109, 'authors': 'Dugald Steer', 'categories': 'Juvenile Fiction', 'thumbnail': 'http://books.google.com/books/content?id=kasIop1plB4C&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'ratings_count': 2139.0, 'isbn10': '0763628107', 'num_pages': 221.0, 'description': "When twelve-year-old Daniel Cook and his sister, Beatrice, spend the summer at a special school run by their parents' eccentric former tutor, they are introduced to the secret study of dragonology and find themselves caught up in an evil plot.", 'average_rating': 3.82, 'title_and_subtitle': "The Dragon's Eye", 'published_year': 2006.0, 'title': "The Dragon's Eye"}, page_content="9780763628109 When twelve-year-old Daniel Cook and his sister, Beatrice, spend the summer at a special school run by their parents' eccentric former tutor, they are introduced to the secret study of dragonology and find themselves caught up in an evil plot."),
 Document(id='faa61a10-039b-4c9a-8c1c-63eb47a0dcc0', metadata={'average_rating': 3.97, 'published_year': 2004.0, 'isbn10': '0786931930', 'isbn13': 9780786931934, 'description': 'An anthology of short fiction captures the world of the diverse dragons of Krynn, along with the dragon-slayers and magic users who study the powerful creatures.', 'authors': 'Margaret Weis', 'thumbnail': 'http://books.google.com/books/content?id=zdriHAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'title_and_subtitle': 'The Search for Power: Dragons of the War of Souls', 'num_pages': 335.0, 'categories': 'Fiction', 'title': 'The Search for Power', 'ratings_count': 287.0}, page_content='9780786931934 An anthology of short fiction captures the world of the diverse dragons of Krynn, along with the dragon-slayers and magic users who study the powerful creatures.'),
 Document(id='db066d48-a329-4119-bbe0-e28cda23f980', metadata={'published_year': 2001.0, 'thumbnail': 'http://books.google.com/books/content?id=exL0mAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'num_pages': 384.0, 'isbn10': '0812574737', 'title_and_subtitle': 'The Dastard', 'categories': 'Fiction', 'average_rating': 3.81, 'title': 'The Dastard', 'authors': 'Piers Anthony', 'description': "Many malevolent menaces have imperiled the magical land of Xanth in its long and storied history. But none has been as despicably dangerous as the Dastard-a craven miscreant who sold his soul to a detestable demon for the power to erase events. Now the entire future of Xanth is at the mercy of his every whim. Only a young dragon-girl named Becka has the power to stop his devious deeds! Becka is a crossbreed-the daughter of Draco Dragon and a lovely human woman who met, by chance, at a Love Spring. Now fourteen, Becka is beginning to wonder where in Xanth she belongs-on the ground with her mother's people, or flying the skies with her father's kind. So she journeys to the Good Magician Humfrey to discover her True Purpose in life. Much to her astonishment and surprise, the Magician tells her that that a great Destiny awaits her-one that will affect the future of all of Xanth.", 'ratings_count': 2960.0, 'isbn13': 9780812574739}, page_content="9780812574739 Many malevolent menaces have imperiled the magical land of Xanth in its long and storied history. But none has been as despicably dangerous as the Dastard-a craven miscreant who sold his soul to a detestable demon for the power to erase events. Now the entire future of Xanth is at the mercy of his every whim. Only a young dragon-girl named Becka has the power to stop his devious deeds! Becka is a crossbreed-the daughter of Draco Dragon and a lovely human woman who met, by chance, at a Love Spring. Now fourteen, Becka is beginning to wonder where in Xanth she belongs-on the ground with her mother's people, or flying the skies with her father's kind. So she journeys to the Good Magician Humfrey to discover her True Purpose in life. Much to her astonishment and surprise, the Magician tells her that that a great Destiny awaits her-one that will affect the future of all of Xanth."),
 Document(id='965318b7-4681-4683-9507-8abfb3f574d1', metadata={'published_year': 2000.0, 'isbn13': 9780595092147, 'title_and_subtitle': 'Firedrake', 'description': "The New York Timesbestselling fantasy author Richard A. Knaak brings to print an epic realm of magic and intrigue! In a land ruled by the shape-lifting Dragon Kings, Cabe Bedlam is hunted for both the legacy he represents and the future he may bring. Yet, dragons may be the least of the dangers, for in a land drenched with sorcery, Cabe's very legacy may be what destroys him!", 'isbn10': '0595092144', 'num_pages': 276.0, 'ratings_count': 619.0, 'categories': 'Fiction', 'average_rating': 3.78, 'authors': 'Richard A. Knaak', 'title': 'Firedrake'}, page_content="9780595092147 The New York Timesbestselling fantasy author Richard A. Knaak brings to print an epic realm of magic and intrigue! In a land ruled by the shape-lifting Dragon Kings, Cabe Bedlam is hunted for both the legacy he represents and the future he may bring. Yet, dragons may be the least of the dangers, for in a land drenched with sorcery, Cabe's very legacy may be what destroys him!"),
 Document(id='073f4ee4-58e5-4b28-baea-0ccb09b731d3', metadata={'categories': 'Juvenile Fiction', 'isbn13': 9780060218058, 'title': 'The Last of the Really Great Whangdoodles', 'average_rating': 4.25, 'ratings_count': 9963.0, 'thumbnail': 'http://books.google.com/books/content?id=D-iftWFTCcgC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'num_pages': 209.0, 'isbn10': '0060218053', 'title_and_subtitle': 'The Last of the Really Great Whangdoodles', 'published_year': 1996.0, 'authors': 'Julie Andrews Edwards', 'description': 'The Whangdoodle was once the wisest, the kindest, and the most extraordinary creature in the world. Then he disappeared and created a wonderful land for himself and all the other remarkable animals -- the ten-legged Sidewinders, the little furry Flukes, the friendly Whiffle Bird, and the treacherous, "oily" Prock. It was an almost perfect place where the last of the really great Whangdoodles could rule his kingdom with "peace, love and a sense of fun"-- apart from and forgotten by people. But not completely forgotten. Professor Savant believed in the Whangdoodle. And when he told the three Potter children of his search for the spectacular creature, Lindy, Tom, and Ben were eager to reach Whangdoodleland. With the Professor\'s help, they discovered the secret way. But waiting for them was the scheming Prock, who would use almost any means to keep them away from his beloved king. Only by skill and determination were the four travelers able to discover the last of the really great Whangdoodles and grant him his heart\'s desire. Julie Andrews Edwards, star of stage and screen, has written a unique and beloved story that has become a modern classic. The Last of the Really Great Whangdoodles is sure to continue to delight readers everywhere. This edition includes a new foreword by the author.'}, page_content='9780060218058 The Whangdoodle was once the wisest, the kindest, and the most extraordinary creature in the world. Then he disappeared and created a wonderful land for himself and all the other remarkable animals -- the ten-legged Sidewinders, the little furry Flukes, the friendly Whiffle Bird, and the treacherous, "oily" Prock. It was an almost perfect place where the last of the really great Whangdoodles could rule his kingdom with "peace, love and a sense of fun"-- apart from and forgotten by people. But not completely forgotten. Professor Savant believed in the Whangdoodle. And when he told the three Potter children of his search for the spectacular creature, Lindy, Tom, and Ben were eager to reach Whangdoodleland. With the Professor\'s help, they discovered the secret way. But waiting for them was the scheming Prock, who would use almost any means to keep them away from his beloved king. Only by skill and determination were the four travelers able to discover the last of the really great Whangdoodles and grant him his heart\'s desire. Julie Andrews Edwards, star of stage and screen, has written a unique and beloved story that has become a modern classic. The Last of the Really Great Whangdoodles is sure to continue to delight readers everywhere. This edition includes a new foreword by the author.'),
 Document(id='efe0a3af-bcb2-4aac-b278-f8824d1ea697', metadata={'description': 'Kit, the young leader of a mysterious tribe possessing the power to transform themselves into dragons, journeys to London to find a rogue drƒkon who has been using his abilities to steal a fortune in jewels, but when he sets a trap for the culprit, he comes face to face with a beautiful and enigmatic young woman. Reprint.', 'isbn10': '0553588044', 'title_and_subtitle': 'The Smoke Thief', 'ratings_count': 6635.0, 'num_pages': 352.0, 'categories': 'Fiction', 'average_rating': 3.74, 'thumbnail': 'http://books.google.com/books/content?id=yHdlXF1ln9MC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'published_year': 2006.0, 'authors': 'Shana Abe', 'title': 'The Smoke Thief', 'isbn13': 9780553588040}, page_content='9780553588040 Kit, the young leader of a mysterious tribe possessing the power to transform themselves into dragons, journeys to London to find a rogue drƒkon who has been using his abilities to steal a fortune in jewels, but when he sets a trap for the culprit, he comes face to face with a beautiful and enigmatic young woman. Reprint.'),
 Document(id='33f2a8c8-ffd9-4ae0-9482-a0d32bcccb5d', metadata={'categories': "Children's stories", 'num_pages': 464.0, 'published_year': 2003.0, 'isbn13': 9780552548229, 'average_rating': 3.8, 'thumbnail': 'http://books.google.com/books/content?id=W6Ev84nWWFoC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'isbn10': '0552548227', 'ratings_count': 184.0, 'title_and_subtitle': "Spindle's End", 'authors': 'Robin McKinley', 'description': '"The princess has been missing since she was a baby. And Rosie, an ordinary girl, is growing up in an unremarkable little village far away from the royal city. nremarkable, that is, in a land where magic is so common that it settles over everything like dust. But a fairy curse is the kind of magic nobody wants, because it always comes true. And Rosie cannot stay ordinary for ever .... obin McKinley, winner of the Newbery Medal, reweaves a classic fantasy tale, sparkling with magic and adventure, some wonderful animals and birds and - of course - fairies, both good and bad."', 'title': "Spindle's End"}, page_content='9780552548229 "The princess has been missing since she was a baby. And Rosie, an ordinary girl, is growing up in an unremarkable little village far away from the royal city. nremarkable, that is, in a land where magic is so common that it settles over everything like dust. But a fairy curse is the kind of magic nobody wants, because it always comes true. And Rosie cannot stay ordinary for ever .... obin McKinley, winner of the Newbery Medal, reweaves a classic fantasy tale, sparkling with magic and adventure, some wonderful animals and birds and - of course - fairies, both good and bad."'),
 Document(id='81811920-73a6-44ab-862b-58fafc512deb', metadata={'isbn10': '0786928573', 'thumbnail': 'http://books.google.com/books/content?id=hihCPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'num_pages': 352.0, 'categories': 'Fiction', 'published_year': 2002.0, 'authors': 'Jean Rabe', 'description': 'As the evil dragon overlords lay waste to once fertile lands, temperate islands, and cool forests, and Dark Knights, draconians, and other foul creatures flock to join the armies of darkness, a small band of heroes struggles to protect all humankind from slavery and cruel death. Reprint.', 'ratings_count': 1337.0, 'isbn13': 9780786928576, 'title': 'The Day of the Tempest', 'title_and_subtitle': 'The Day of the Tempest', 'average_rating': 3.65}, page_content='9780786928576 As the evil dragon overlords lay waste to once fertile lands, temperate islands, and cool forests, and Dark Knights, draconians, and other foul creatures flock to join the armies of darkness, a small band of heroes struggles to protect all humankind from slavery and cruel death. Reprint.'),
 Document(id='a607cad3-4072-4b53-9333-32fc6f8971d2', metadata={'categories': 'Fiction', 'isbn13': 9780765345905, 'title_and_subtitle': 'Wolfskin', 'average_rating': 4.0, 'published_year': 2004.0, 'thumbnail': 'http://books.google.com/books/content?id=ChyHmAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'ratings_count': 5531.0, 'title': 'Wolfskin', 'isbn10': '0765345900', 'num_pages': 544.0, 'authors': 'Juliet Marillier', 'description': "All young Eyvind ever wanted was to become a great Viking warrior--a Wolfskin--and carry honor out in the name of his fathergod Thor. He can think of no future more glorious. The chance to make it happen is his when his chieftain Ulf is brought the tale of a magical land across the sea, a place where men with courage could go to conquer a land and bring glory to themselves. They set out to find this fabled land, and discover a windswept and barren place, but one filled with unexpected beauty and hidden treasures... and a people who are willing to share their bounty. Ulf's new settlement begins in harmony with the natives of the isles led by the gentle king Engus. And Eyvind finds a treasure of his own in the young Nessa, niece of the King, seer and princess. His life will change forever as she claims his heart for her own. But someone has come along to this new land who is not what he seems. Somerled, a strange and lonely boy that Eyvind befriended long ago has a secret--and his own plans for the future. The blood oath that they swore in childhood binds them in lifelong loyalty, and Somerled is calling in the debt of honor. What he asks of Eyvind might just doom him to kill the only thing that Evyind has ever truly loved. Will the price of honor create the destruction of all that Eyvind holds dear?"}, page_content="9780765345905 All young Eyvind ever wanted was to become a great Viking warrior--a Wolfskin--and carry honor out in the name of his fathergod Thor. He can think of no future more glorious. The chance to make it happen is his when his chieftain Ulf is brought the tale of a magical land across the sea, a place where men with courage could go to conquer a land and bring glory to themselves. They set out to find this fabled land, and discover a windswept and barren place, but one filled with unexpected beauty and hidden treasures... and a people who are willing to share their bounty. Ulf's new settlement begins in harmony with the natives of the isles led by the gentle king Engus. And Eyvind finds a treasure of his own in the young Nessa, niece of the King, seer and princess. His life will change forever as she claims his heart for her own. But someone has come along to this new land who is not what he seems. Somerled, a strange and lonely boy that Eyvind befriended long ago has a secret--and his own plans for the future. The blood oath that they swore in childhood binds them in lifelong loyalty, and Somerled is calling in the debt of honor. What he asks of Eyvind might just doom him to kill the only thing that Evyind has ever truly loved. Will the price of honor create the destruction of all that Eyvind holds dear?"),
 Document(id='3ae0bdf0-9e8f-4437-a2cb-4656ae78396f', metadata={'average_rating': 3.77, 'title': 'Rose Daughter', 'ratings_count': 16756.0, 'isbn10': '0441005837', 'num_pages': 304.0, 'thumbnail': 'http://books.google.com/books/content?id=RtiQPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'published_year': 1998.0, 'authors': 'Robin McKinley', 'title_and_subtitle': 'Rose Daughter', 'categories': 'Juvenile Fiction', 'isbn13': 9780441005833, 'description': 'The winner of the Newbery Award for The Hero and the Crown returns to the fairy tale of the Beauty and the Beast to create a haunting portrayal of the transformative power of love. Reprint. PW.'}, page_content='9780441005833 The winner of the Newbery Award for The Hero and the Crown returns to the fairy tale of the Beauty and the Beast to create a haunting portrayal of the transformative power of love. Reprint. PW.')]

In [7]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3586,9780763628109,0763628107,The Dragon's Eye,Dugald Steer,Juvenile Fiction,http://books.google.com/books/content?id=kasIo...,When twelve-year-old Daniel Cook and his siste...,2006.0,3.82,221.0,2139.0,The Dragon's Eye,9780763628109 When twelve-year-old Daniel Cook...

In [8]:
def get_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)].head(top_k)